name: Send the daily poem
on:
  schedule:
    - cron: '0 12 * * *' # hourly # daily at 12:00 UTC (07:00 EST)

jobs:
  run_tests:
    name: Send a daily poem at noon UTC
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Curate a poem, and send it to the listserv
        run:
          python send-poem.py --type 'daily' --username 'poemsfromtom@gmail.com' --password ${{ secrets.PFT_PW }} --listserv_filename 'poems/listserv.csv'
          --github_repo_name 'thomaswmorris.github.io' --github_token ${{ secrets.GH_TOKEN }}

      - name: Update repo pages
        run:
          python make-docs.py --github_repo_name 'thomaswmorris.github.io' --github_token ${{ secrets.GH_TOKEN }} 