name: Poem of the day
on:
  schedule:
    - cron: "0 11 * * *" # daily at 11:00 UTC (usually 06:00 EST)
  workflow_dispatch:

jobs:
  run_tests:
    name: Send the poem of the day
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip install -v .

      - name: Curate a poem, and send it to the listserv
        run:
          python scripts/send-poem.py --kind "daily" --username "poemsfromtom@gmail.com" --password ${{ secrets.PFT_PW }} --listserv_filename "data/poems/listserv.csv"
          --github_repo_name "thomaswmorris.github.io" --github_token ${{ secrets.GH_TOKEN }} --write_to_repo
