name: Hourly test
on:
  schedule:
    - cron: "55 0-9,11-23 * * *" # hourly, except at 12:00 UTC (07:00 EST)

jobs:
  run_tests:
    name: Send a test poem every hour
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -v .

      - name: Curate a poem, and send it to the testserv
        run:
          python scripts/send_poem.py --mode "hourly-test" --username "poemsfromtom@gmail.com" --password ${{ secrets.PFT_PW }} --listserv_filename "poems/testserv.csv"
          --github_repo_name "thomaswmorris.github.io" --github_token ${{ secrets.GH_TOKEN }}