name: Test poem on push

on: push

jobs:
  run_tests:
    name: Test send-poem.py with credentials
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send poem to myself
        run:
          python send-poem.py --username 'poemsfromtom@gmail.com' --password ${{ secrets.PFT_PW }} --repo_lsfn 'testserv.csv'
          --repo 'poetry' --token ${{ secrets.GH_TOKEN }} --subj_tag 'Poem of the Day | ' --context true --rh true --wh true --hist_tag 'test'
