name: Send a test poem on a push to master
on: push

jobs:
  run_tests:
    name: Test send-poem.py and make-docs.py with credentials
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send poem to myself
        run:
          python poetry/send-poem.py --type 'test' --username 'poemsfromtom@gmail.com' --password ${{ secrets.PFT_PW }} --listserv_filename 'poems/testserv.csv'
          --repo 'thomaswmorris.github.io' --token ${{ secrets.GH_TOKEN }} --context true --rh true --wh true --vv true

      - name: Update repo pages
        run:
          python poetry/make-docs.py --repo 'thomaswmorris.github.io' --token ${{ secrets.GH_TOKEN }} 