name: Test
on: push

jobs:
  run_tests:
    name: Test send-poem.py with credentials
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Send poem to myself
        run:
          python poetry/send-poem.py --type 'test' --username 'poemsfromtom@gmail.com' --password ${{ secrets.PFT_PW }} --repo_lsfn 'testserv.csv'
          --repo 'poems' --token ${{ secrets.GH_TOKEN }} --subj_tag '(PUSH) ' --context true --rh true --wh true --vv true