name: Test poem on push

on: push

jobs:
  run_tests:
    name: Test sirepo-bluesky with ${{ matrix.docker-binary }} and Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Set env vars
        run: |

          export PFT_PW=${{ secrets.PFT_PW }}
          echo "PFT_PASSWORD=${PFT_PW}" 

          export GH_TOKEN=${{ secrets.GH_TOKEN }}
          echo "GH_TOKEN=${GH_TOKEN}" 

      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip list

      - name: Send poem to myself
        run:
          python send-poem.py --username 'poemsfromtom@gmail.com' --password "${GH_TOKEN}" --address 'poemsfromtom@gmail.com' 
          --subj_tag 'Poem of the Day | ' --context true --wh true --rh true --hist_tag 'daily'
