name: Pages
on: push

jobs:
  run_tests:
    name: Test send-poem.py with credentials
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Update repo pages
        run:
          python poetry/make-docs.py --repo 'poetry' --token ${{ secrets.GH_TOKEN }} 